version: '3'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  python:
    build:
      context: ./api
    depends_on:
      - database
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:5432/${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - ADMINS=${ADMIN_MAIL}
    volumes:
      - ./api:/app
    ports:
      - "8000:5000"

  client:
    build:
      context: ./client
      target: dev
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - python
    environment:
       - NEXT_PUBLIC_API_CLIENT_ENTRYPOINT=${NEXT_PUBLIC_API_CLIENT_ENTRYPOINT}
       - NEXT_API_SERVER_ENTRYPOINT=${NEXT_API_SERVER_ENTRYPOINT}
       - NEXT_CLIENT_ENTRYPOINT=${NEXT_CLIENT_ENTRYPOINT}
    ports:
      - "3000:3000"