
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://sgwt-cdn-sgbs.sgmarkets.com/sg-bootstrap/5.0.0/core/css/sg-bootstrap-standard.min.css" />
        <link rel="stylesheet" href="https://sgwt-cdn-sgbs.sgmarkets.com/sg-bootstrap/5.0.0/icons/index.min.css" />
      </head>
      <body>
      <section>
      <nav className="navbar navbar-expand-lg bg-body-tertiary border-bottom mb-3">
        <div className="container-fluid">
          <a className="navbar-brand" href="#">
            <svg height="32" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
              <g>
                <rect fill="#e60028" width="32" height="16"></rect>
                <rect fill="#000" y="16" width="32" height="16"></rect>
                <rect fill="#fff" x="6" y="15" width="20" height="2"></rect>
              </g>
            </svg>
          </a>
          <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarSupportedContent">
            <ul className="navbar-nav me-auto mb-2 mb-lg-0">
              <li className="nav-item">
                <a className="nav-link active" aria-current="page" href="#">Home</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      </section>
      
        {children}
      </body>
    </html>
  )
}
