"""added boolean on client AR - can edit

Revision ID: 0f6fbec2699e
Revises: 7e91b78428c5
Create Date: 2023-05-09 11:48:58.161682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6fbec2699e'
down_revision = '7e91b78428c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_rights_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canEdit', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_rights_client', schema=None) as batch_op:
        batch_op.drop_column('canEdit')

    # ### end Alembic commands ###
