"""added client data to widget data

Revision ID: 2ab2725a01bf
Revises: 404e9aaea69c
Create Date: 2023-04-10 19:03:29.652242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab2725a01bf'
down_revision = '404e9aaea69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('widget_data_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'widget_data', ['widget_data_id'], ['id'])

    with op.batch_alter_table('widget_data', schema=None) as batch_op:
        batch_op.drop_constraint('widget_data_client_id_fkey', type_='foreignkey')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('widget_data_client_id_fkey', 'client', ['client_id'], ['id'])

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('widget_data_id')

    # ### end Alembic commands ###
