"""added client data to widget data

Revision ID: 404e9aaea69c
Revises: a8786dd23d1d
Create Date: 2023-04-10 18:59:02.889485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404e9aaea69c'
down_revision = 'a8786dd23d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
