"""added opportunities, modified widget and widget data

Revision ID: 9614d3fcaaa6
Revises: 0f6fbec2699e
Create Date: 2023-05-14 17:21:29.525306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9614d3fcaaa6'
down_revision = '0f6fbec2699e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('sme', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('size', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=255), nullable=False))

    with op.batch_alter_table('widget_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('important', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('opportunity_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pods', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'opportunity', ['opportunity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pods')
        batch_op.drop_column('opportunity_id')
        batch_op.drop_column('important')

    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('size')
        batch_op.drop_column('position')

    op.drop_table('opportunity')
    # ### end Alembic commands ###
