"""added teams

Revision ID: 96226748586d
Revises: d28fb3c5dfc6
Create Date: 2023-05-09 09:47:44.649840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96226748586d'
down_revision = 'd28fb3c5dfc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('sponsor',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('team_banker_key', type_='unique')
        batch_op.drop_constraint('team_deputy_sponsor_key', type_='unique')
        batch_op.drop_constraint('team_nextgen_key', type_='unique')
        batch_op.drop_constraint('team_nextgen_fkey', type_='foreignkey')
        batch_op.drop_constraint('team_deputy_sponsor_fkey', type_='foreignkey')
        batch_op.drop_constraint('team_banker_fkey', type_='foreignkey')
        batch_op.drop_column('deputy_sponsor')
        batch_op.drop_column('nextgen')
        batch_op.drop_column('banker')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banker', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nextgen', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('deputy_sponsor', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('team_banker_fkey', 'user', ['banker'], ['id'])
        batch_op.create_foreign_key('team_deputy_sponsor_fkey', 'user', ['deputy_sponsor'], ['id'])
        batch_op.create_foreign_key('team_nextgen_fkey', 'user', ['nextgen'], ['id'])
        batch_op.create_unique_constraint('team_nextgen_key', ['nextgen'])
        batch_op.create_unique_constraint('team_deputy_sponsor_key', ['deputy_sponsor'])
        batch_op.create_unique_constraint('team_banker_key', ['banker'])
        batch_op.alter_column('sponsor',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
