"""modified widget type

Revision ID: a391f885da1c
Revises: 9614d3fcaaa6
Create Date: 2023-05-16 21:17:01.819453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a391f885da1c'
down_revision = '9614d3fcaaa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('widget_type', sa.String(length=255), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('widget_type')

    # ### end Alembic commands ###
