"""first migration

Revision ID: a8786dd23d1d
Revises: 
Create Date: 2023-04-10 10:31:09.373567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8786dd23d1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('bdr_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('widget_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('widget_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_widget_data_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widget_data_timestamp'))

    op.drop_table('widget_data')
    op.drop_table('widget')
    op.drop_table('client')
    # ### end Alembic commands ###
